# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "crAPI"
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "crapi"
  config.vm.network "private_network", ip: "192.168.33.20"
  config.vm.synced_folder "../../", "/tmp/crapi"

  config.vm.provision :shell do |shell|
    shell.privileged = true
    shell.path = "provisioner.sh"
  end

end
