apiVersion: v1
kind: ConfigMap
metadata:
  name: crapi-workshop-configmap
  labels:
    app: crapi-workshop
data:
    IDENTITY_SERVICE: crapi-identity:8080
    SECRET_KEY: crapi
    DB_HOST: postgresdb
    DB_DRIVER: postgres
    DB_USER: admin
    DB_PASSWORD: crapisecretpassword
    DB_NAME: crapi
    DB_PORT: "5432"
    MONGO_DB_HOST: mongodb
    MONGO_DB_DRIVER: mongodb
    MONGO_DB_PORT: "27017"
    MONGO_DB_USER: admin
    MONGO_DB_PASSWORD: crapisecretpassword
    MONGO_DB_NAME: crapi
    SERVER_PORT: "8000"
    API_GATEWAY_URL: "https://api.crapi.io"
    TLS_ENABLED: "true"
    TLS_CERTIFICATE: certs/server.crt
    TLS_KEY: certs/server.key      
