apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.community.config.name }}
  labels:
    release: {{ .Release.Name }}
    {{- with .Values.community.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
    IDENTITY_SERVICE: {{ .Values.identity.service.name }}:{{ .Values.identity.port }}
    DB_HOST: {{ .Values.postgresdb.service.name }}
    DB_DRIVER: {{ .Values.community.config.postgresDbDriver }}
    DB_USER: {{ .Values.postgresdb.config.postgresUser }}
    DB_PASSWORD: {{ .Values.postgresdb.config.postgresPassword }}
    DB_NAME: {{ .Values.postgresdb.config.postgresDbName }}
    DB_PORT: {{ .Values.postgresdb.port | quote }}
    MONGO_DB_HOST: {{ .Values.mongodb.service.name }}
    MONGO_DB_DRIVER: {{ .Values.community.config.mongoDbDriver }}
    MONGO_DB_PORT: {{ .Values.mongodb.port | quote }}
    MONGO_DB_USER: {{ .Values.mongodb.config.mongoUser }}
    MONGO_DB_PASSWORD: {{ .Values.mongodb.config.mongoPassword }}
    MONGO_DB_NAME: {{ .Values.mongodb.config.mongoDbName }}
    SERVER_PORT: {{ .Values.community.port | quote }}
    TLS_ENABLED: {{ .Values.tlsEnabled | quote }}
