apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.workshop.config.name }}
  labels:
    release: {{ .Release.Name }}
    {{- toYaml .Values.workshop.config.labels | nindent 4 }}
data:
    IDENTITY_SERVICE: {{ .Values.identity.service.name }}:{{ .Values.identity.port }}
    SECRET_KEY: {{ .Values.workshop.config.secretKey }}
    DB_HOST: {{ .Values.postgresdb.service.name }}
    DB_DRIVER: {{ .Values.workshop.config.postgresDbDriver }}
    DB_USER: {{ .Values.postgresdb.config.postgresUser }}
    DB_PASSWORD: {{ .Values.postgresdb.config.postgresPassword }}
    DB_NAME: {{ .Values.postgresdb.config.postgresDbName }}
    DB_PORT: {{ .Values.postgresdb.port | quote }}
    MONGO_DB_HOST: {{ .Values.mongodb.service.name }}
    MONGO_DB_DRIVER: {{ .Values.workshop.config.mongoDbDriver }}
    MONGO_DB_PORT: {{ .Values.mongodb.port | quote }}
    MONGO_DB_USER: {{ .Values.mongodb.config.mongoUser }}
    MONGO_DB_PASSWORD: {{ .Values.mongodb.config.mongoPassword }}
    MONGO_DB_NAME: {{ .Values.mongodb.config.mongoDbName }}
    SERVER_PORT: {{ .Values.workshop.port | quote }}
    API_GATEWAY_URL: {{ if .Values.apiGatewayServiceInstall }}"https://{{ .Values.apiGatewayService.service.name }}"{{ else }}{{ .Values.apiGatewayServiceUrl }}{{ end }}
    TLS_ENABLED: {{ .Values.tlsEnabled | quote }}
