apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workshop.service.name }}
  labels:
    release: {{ .Release.Name }}
    {{- with .Values.workshop.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.workshop.port }}
    name: python
  selector:
    {{- toYaml .Values.workshop.serviceSelectorLabels | nindent 4 }}
