# Default values for crapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
imagePullPolicy: IfNotPresent

enableLog4j: true
enableShellInjection: true

web:
  image: crapi/crapi-web
  port: 80
identity:
  image: crapi/crapi-identity
  port: 8080
community-graphql:
  image: crapi/crapi-community-graphql
  port: 8087
community-grpc:
  image: crapi/crapi-community-grpc
  port: 9090
workshop:
  image: crapi/crapi-workshop
  port: 8000
mailhog:
  image: crapi/mailhog
  webPort: 8025
mongodb:
  image: mongo
  version: 5.0
postgresdb:
  image: postgres
  version: 14
