apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mailhog.smtpService.name }}
  namespace: {{ .Values.mailhog.namespace }}
  labels:
    release: {{ .Release.Name }}
    {{- with .Values.mailhog.smtpService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: smtp
    port: {{ .Values.mailhog.smtpPort }}
    protocol: TCP
  selector:
    {{- toYaml .Values.mailhog.serviceSelectorLabels | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
