package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"
	"errors"
	"log"
	"os"
	"time"

	"crapi.community/graphql.grpc/graph/config"
	"crapi.community/graphql.grpc/graph/model"
	"crapi.community/graphql.grpc/grpc/models"
	pb "crapi.community/graphql.grpc/grpc/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// CreatePost is the resolver for the CreatePost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.PostInput) (*model.Post, error) {
	post := models.PrepareNewPost(model.Post{
		Title:   input.Title,
		Content: input.Content,
	})

	conn, err := grpc.Dial(os.Getenv("GRPC-SERVICE"), grpc.WithInsecure())
	if err != nil {
		log.Println("Cannot connect to server, %v", err)
		return &model.Post{}, err
	}
	defer conn.Close()

	client := pb.NewCommunityServiceClient(conn)

	ctx = metadata.NewOutgoingContext(
		ctx,
		metadata.Pairs("key1", "val1", "key2", "val2"),
	)
	p := models.Convert_Graph_pb_post(post)
	_, err = client.CreatePost(ctx, &pb.CreatePostRequest{
		Post: p,
	})

	if err != nil {
		log.Println("Failed creating a post, %v", err)
		return &model.Post{}, err
	}
	ret := models.Convert_pb_Graph_post(p)
	return &ret, nil
}

// CreateCoupon is the resolver for the CreateCoupon field.
func (r *mutationResolver) CreateCoupon(ctx context.Context, input model.CouponInput) (*model.Coupon, error) {
	coupon := models.PrepareNewCoupon(input)

	conn, err := grpc.Dial(os.Getenv("GRPC-SERVICE"), grpc.WithInsecure())
	if err != nil {
		log.Println("Cannot connect to server, %v", err)
		return &model.Coupon{}, err
	}
	defer conn.Close()

	client := pb.NewCommunityServiceClient(conn)

	ctx = metadata.NewOutgoingContext(
		ctx,
		metadata.Pairs("key1", "val1", "key2", "val2"),
	)

	_, err = client.CreateCoupon(ctx, &pb.CreateCouponRequest{
		Coupon: &pb.Coupon{
			CouponCode: coupon.CouponCode,
			Amount:     coupon.Amount,
			CreatedAt:  timestamppb.New(coupon.CreatedAt),
		}})

	if err != nil {
		log.Println("Failed creating a Coupon, %v", err)
		return &model.Coupon{}, err
	}
	return &coupon, nil
}

// AddComment is the resolver for the AddComment field.
func (r *mutationResolver) AddComment(ctx context.Context, input *model.CommentInput) (*model.Post, error) {
	conn, err := grpc.Dial(os.Getenv("GRPC-SERVICE"), grpc.WithInsecure())
	if err != nil {
		log.Println("Cannot connect to server, %v", err)
		return &model.Post{}, err
	}
	defer conn.Close()

	client := pb.NewCommunityServiceClient(conn)

	ctx = metadata.NewOutgoingContext(
		ctx,
		metadata.Pairs("key1", "val1", "key2", "val2"),
	)

	user := models.PrepareUser()
	_, err = client.CreateComment(ctx, &pb.CreateCommentRequest{
		Comment: &pb.Comment{
			Id:        input.ID,
			Content:   input.Content,
			CreatedAt: timestamppb.New(time.Now()),
			Author: &pb.User{
				Nickname:  user.Nickname,
				Email:     user.Email,
				VehicleId: user.Vehicleid,
				Picurl:    user.ProfilePicURL,
				CreatedAt: timestamppb.New(user.CreatedAt),
			},
		},
	})

	if err != nil {
		log.Println("Can not add comment to post")
		return &model.Post{}, err
	}
	retPost, err := client.GetPosts(ctx, &pb.GetPostsRequest{
		Ids: []string{input.ID},
	})
	if err != nil {
		log.Println("Failed to fetch the post after adding comment, %v", err)
		return &model.Post{}, err
	}

	p_model := models.Convert_pb_Graph_post(retPost.GetPosts()[0])
	return &p_model, nil
}

// GetPosts is the resolver for the GetPosts field.
func (r *queryResolver) GetPosts(ctx context.Context, ids []string) ([]*model.Post, error) {
	// lis := []string{"oBvaQhfFqVWVdDBgAhaER6", "MnwSHsuN9okaPEiSerDuA3"}
	conn, err := grpc.Dial(os.Getenv("GRPC-SERVICE"), grpc.WithInsecure())
	if err != nil {
		log.Println("Cannot connect to server, %v", err)
		return nil, err
	}
	defer conn.Close()

	client := pb.NewCommunityServiceClient(conn)

	ctx = metadata.NewOutgoingContext(
		ctx,
		metadata.Pairs("key1", "val1", "key2", "val2"),
	)

	GetPosts, err := client.GetPosts(ctx, &pb.GetPostsRequest{
		Ids: ids,
	})

	if err != nil {
		println("GetPosts() failed .... recieved no response from grpc server ... , %v", err)
		return nil, err
	}

	retPost := []*model.Post{}
	for i := 0; i < len(GetPosts.GetPosts()); i++ {
		convertedP := models.Convert_pb_Graph_post(GetPosts.GetPosts()[i])
		retPost = append(retPost, &convertedP)
	}

	return retPost, nil
}

// GetAllPosts is the resolver for the GetAllPosts field.
func (r *queryResolver) GetAllPosts(ctx context.Context, limit int) ([]*model.Post, error) {
	// In this function, we are bypassing the connection with grpc_client and directly communicating with grpc_server
	conn, err := grpc.Dial(os.Getenv("GRPC-SERVICE"), grpc.WithInsecure())
	if err != nil {
		log.Println("Cannot connect to server, %v", err)
		return nil, err
	}
	defer conn.Close()
	client := pb.NewCommunityServiceClient(conn)

	ctx = context.Background()
	ctx = metadata.NewOutgoingContext(
		ctx,
		metadata.Pairs("key1", "val1", "key2", "val2"),
	)

	GetPosts, err := client.GetAllPosts(ctx, &pb.GetAllPostRequest{
		NoOfPosts: int32(limit),
	})
	if err != nil {
		log.Println("GetPost failed ... could not get posts from grpc")
		return nil, err
	}
	retPost := []*model.Post{}
	for i := 0; i < len(GetPosts.GetPosts()); i++ {
		convertedP := models.Convert_pb_Graph_post(GetPosts.GetPosts()[i])
		retPost = append(retPost, &convertedP)
	}
	return retPost, nil
}

// ValidateCoupon is the resolver for the ValidateCoupon field.
func (r *queryResolver) ValidateCoupon(ctx context.Context, code string) (*model.Coupon, error) {
	if code == "" {
		return nil, errors.New("Coupon Code empty")
	}

	conn, err := grpc.Dial(os.Getenv("GRPC-SERVICE"), grpc.WithInsecure())
	if err != nil {
		log.Println("Cannot connect to server, %v", err)
		return nil, err
	}
	defer conn.Close()

	client := pb.NewCommunityServiceClient(conn)
	ctx = context.Background()
	ctx = metadata.NewOutgoingContext(
		ctx,
		metadata.Pairs("key1", "val1", "key2", "val2"),
	)

	log.Println("All connections have been made .... validating coupon now")
	coupon, err := client.ValidateCoupon(ctx, &pb.ValidateCouponRequest{
		CouponCode: code,
	})

	if err != nil {
		log.Println("Coupon does not exist")
		return nil, err
	}
	return &model.Coupon{
		CouponCode: coupon.Coupon.GetCouponCode(),
		Amount:     coupon.Coupon.GetAmount(),
		CreatedAt:  models.Convert_to_Time(coupon.Coupon.GetCreatedAt()),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var server = config.Server{}
